language: node_js
node_js:
    - "stable"
cache:
    directories:
        - node_modules
script:
    - npm run build
deploy:
    provider: heroku
    api_key:
        secure: 481b1f57-9036-4b49-ae28-b799ddc92b87
    app: trello-copy-frontend
    on:
        branch: master